// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blbsqooxwyapcxsfgope.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsYnNxb294d3lhcGN4c2Znb3BlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDMxNzYsImV4cCI6MjA2NDc3OTE3Nn0.qetw8yqRyvb3jNBnzDpfIVAq3sWTBX3drEtLsF-OMwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);