// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edjtsiynyhrnulfgwbkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkanRzaXlueWhybnVsZmd3YmtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NzMzODksImV4cCI6MjA4NjA0OTM4OX0.cYXCrjLqfMm-FDZZP_so4USHD4B3HPdkpoJTS-1KCeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});